name: transmicron
channels:
  - intel
  - anaconda
  - conda-forge
  - bioconda
  - defaults
  - plotly
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3.2
  - amply=0.1.5
  - appdirs=1.4.4
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attmap=0.13.2
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - beautifulsoup4=4.11.1
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-annotationdbi=1.54.0
  - bioconductor-annotationhub=3.0.0
  - bioconductor-annotatr=1.18.0
  - bioconductor-biobase=2.52.0
  - bioconductor-biocfilecache=2.0.0
  - bioconductor-biocgenerics=0.38.0
  - bioconductor-biocio=1.2.0
  - bioconductor-biocparallel=1.26.0
  - bioconductor-biocversion=3.13.1
  - bioconductor-biomart=2.48.0
  - bioconductor-biostrings=2.60.0
  - bioconductor-bsgenome=1.60.0
  - bioconductor-bsgenome.hsapiens.ucsc.hg38=1.4.3
  - bioconductor-bsgenome.mmusculus.ucsc.mm10=1.4.0
  - bioconductor-bsgenome.mmusculus.ucsc.mm9=1.4.0
  - bioconductor-bumphunter=1.34.0
  - bioconductor-complexheatmap=2.8.0
  - bioconductor-delayedarray=0.18.0
  - bioconductor-genomeinfodb=1.28.0
  - bioconductor-genomeinfodbdata=1.2.7
  - bioconductor-genomicalignments=1.28.0
  - bioconductor-genomicfeatures=1.44.0
  - bioconductor-genomicranges=1.44.0
  - bioconductor-interactivedisplaybase=1.30.0
  - bioconductor-iranges=2.26.0
  - bioconductor-keggrest=1.32.0
  - bioconductor-limma=3.48.0
  - bioconductor-matrixgenerics=1.4.0
  - bioconductor-org.hs.eg.db=3.13.0
  - bioconductor-org.mm.eg.db=3.13.0
  - bioconductor-plyranges=1.12.0
  - bioconductor-regioner=1.24.0
  - bioconductor-rhdf5=2.38.0
  - bioconductor-rhdf5filters=1.6.0
  - bioconductor-rhdf5lib=1.16.0
  - bioconductor-rhtslib=1.24.0
  - bioconductor-rsamtools=2.8.0
  - bioconductor-rtracklayer=1.52.0
  - bioconductor-s4vectors=0.30.0
  - bioconductor-summarizedexperiment=1.22.0
  - bioconductor-txdb.mmusculus.ucsc.mm10.knowngene=3.10.0
  - bioconductor-txdb.mmusculus.ucsc.mm9.knowngene=3.2.2
  - bioconductor-xvector=0.32.0
  - bioconductor-zlibbioc=1.38.0
  - blosc=1.21.1
  - boto3=1.22.7
  - botocore=1.25.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.0.0
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.0
  - chardet=4.0.0
  - charset-normalizer=2.0.12
  - coincbc=2.10.5
  - colorama=0.4.4
  - conda=4.13.0
  - conda-build=3.21.9
  - conda-package-handling=1.8.1
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - cryptography=36.0.2
  - curl=7.83.0
  - cycler=0.11.0
  - datrie=0.8.2
  - dbus=1.13.6
  - debugpy=1.6.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.18.1
  - dropbox=11.30.0
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.8
  - filechunkio=1.8
  - filelock=3.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.33.3
  - freetype=2.10.4
  - fribidi=1.0.10
  - frozenlist=1.3.0
  - ftputil=5.0.3
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glob2=0.7
  - google-api-core=2.5.0
  - google-api-python-client=2.47.0
  - google-auth=2.6.6
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.2.2
  - google-cloud-storage=2.1.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.1.0
  - googleapis-common-protos=1.56.0
  - graphite2=1.3.13
  - grpcio=1.45.0
  - gsl=2.6
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - h5py=3.6.0
  - harfbuzz=2.9.1
  - hdf5=1.12.1
  - httplib2=0.20.4
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - importlib_resources=5.7.1
  - iniconfig=1.1.1
  - ipykernel=6.15.0
  - ipython=8.4.0
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - jmespath=1.0.0
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter_client=7.0.6
  - jupyter_core=4.9.2
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libarchive=3.5.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.83.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblief=0.11.5
  - libllvm11=11.1.0
  - libnghttp2=1.47.0
  - libogg=1.3.4
  - libopenblas=0.3.20
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.20.0
  - libsanitizer=9.4.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.11
  - logmuse=0.2.6
  - lsd=2.2.3
  - lz4-c=1.9.3
  - lzo=2.10
  - make=4.3
  - markupsafe=2.1.1
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.3
  - mock=4.0.3
  - multidict=6.0.2
  - munkres=1.1.4
  - mysql-common=8.0.29
  - mysql-libs=8.0.29
  - nbformat=5.4.0
  - ncurses=6.2
  - nest-asyncio=1.5.5
  - nomkl=1.0
  - nspr=4.32
  - nss=3.72
  - numexpr=2.8.0
  - numpy=1.22.3
  - oauth2client=4.1.3
  - openjdk=11.0.9.1
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.18
  - pango=1.48.10
  - paramiko=2.10.4
  - parso=0.8.3
  - patchelf=0.14.5
  - pcre=8.45
  - pcre2=10.37
  - peppy=0.31.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - pip=22.0.4
  - pixman=0.40.0
  - pkginfo=1.8.3
  - plac=1.3.5
  - pluggy=1.0.0
  - ply=3.11
  - prettytable=3.2.0
  - prompt-toolkit=3.0.29
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.6.0
  - pure_eval=0.2.2
  - py=1.11.0
  - py-lief=0.11.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.12.0
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.8
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.18.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytables=3.7.0
  - pytest=7.1.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python-irodsclient=1.1.3
  - python-libarchive-c=4.0
  - python-tzdata=2022.1
  - python_abi=3.9
  - pytz=2022.1
  - pytz-deprecation-shim=0.1.0.post0
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=19.0.2
  - qt=5.12.9
  - r-alphavantager=0.1.2
  - r-anytime=0.3.9
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.1.1
  - r-base64enc=0.1_3
  - r-bh=1.78.0_0
  - r-bibtex=0.4.2.3
  - r-biocmanager=1.30.17
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.3
  - r-brio=1.1.3
  - r-broom=0.8.0
  - r-bslib=0.3.1
  - r-cachem=1.0.6
  - r-cairo=1.5_15
  - r-calibrate=1.7.7
  - r-callr=3.7.0
  - r-caret=6.0_89
  - r-cellranger=1.1.0
  - r-cimpl=1.1
  - r-circlize=0.4.14
  - r-class=7.3_20
  - r-cli=3.3.0
  - r-clipr=0.8.0
  - r-clue=0.3_60
  - r-cluster=2.1.3
  - r-codetools=0.2_18
  - r-colorspace=2.0_3
  - r-commonmark=1.8.0
  - r-complexupset=1.3.3
  - r-conflicted=1.1.0
  - r-cowplot=1.1.1
  - r-cpp11=0.4.2
  - r-crayon=1.5.1
  - r-crosstalk=1.2.0
  - r-curl=4.3.2
  - r-data.table=1.14.2
  - r-dbi=1.1.2
  - r-dbplyr=2.1.1
  - r-desc=1.4.1
  - r-dials=0.1.1
  - r-dicedesign=1.9
  - r-diffobj=0.3.5
  - r-digest=0.6.29
  - r-doparallel=1.0.16
  - r-dorng=1.8.2
  - r-dplyr=1.0.9
  - r-dt=0.22
  - r-dtplyr=1.2.1
  - r-e1071=1.7_9
  - r-ellipsis=0.3.2
  - r-evaluate=0.15
  - r-fansi=1.0.3
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-filelock=1.0.2
  - r-fmstable=0.1_2
  - r-fontawesome=0.2.2
  - r-forcats=0.5.1
  - r-foreach=1.5.2
  - r-forecast=8.16
  - r-formatr=1.12
  - r-fracdiff=1.5_1
  - r-fs=1.5.2
  - r-furrr=0.3.0
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.25.0
  - r-future.apply=1.9.0
  - r-gargle=1.2.0
  - r-gdtools=0.2.4
  - r-generics=0.1.2
  - r-getoptlong=1.0.5
  - r-ggforce=0.3.3
  - r-ggformula=0.10.1
  - r-ggplot2=3.3.6
  - r-ggridges=0.5.3
  - r-ggseqlogo=0.1
  - r-ggstance=0.3.5
  - r-globaloptions=0.1.2
  - r-globals=0.14.0
  - r-glue=1.6.2
  - r-googledrive=2.0.0
  - r-googlesheets4=1.0.0
  - r-gower=1.0.0
  - r-gpfit=1.0_8
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-hardhat=0.2.0
  - r-harmonicmeanp=3.0
  - r-haven=2.4.3
  - r-hexbin=1.28.2
  - r-highr=0.9
  - r-hms=1.1.1
  - r-htmltools=0.5.2
  - r-htmlwidgets=1.5.4
  - r-httpuv=1.6.5
  - r-httr=1.4.3
  - r-ids=1.0.1
  - r-infer=1.0.0
  - r-ipred=0.9_12
  - r-isoband=0.2.5
  - r-iterators=1.0.14
  - r-janitor=2.1.0
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.0
  - r-kernsmooth=2.23_20
  - r-knitr=1.39
  - r-labeling=0.4.2
  - r-labelled=2.9.1
  - r-lambda.r=1.2.4
  - r-later=1.2.0
  - r-lattice=0.20_45
  - r-lava=1.6.10
  - r-lazyeval=0.2.2
  - r-lhs=1.1.5
  - r-lifecycle=1.0.1
  - r-listenv=0.8.0
  - r-lmtest=0.9_40
  - r-locfit=1.5_9.5
  - r-lsd=4.1_0
  - r-lubridate=1.8.0
  - r-magrittr=2.0.3
  - r-mass=7.3_57
  - r-matrix=1.4_1
  - r-matrixstats=0.62.0
  - r-memoise=2.0.1
  - r-mgcv=1.8_40
  - r-mime=0.12
  - r-modeldata=0.1.1
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.8
  - r-mosaiccore=0.9.0
  - r-munsell=0.5.0
  - r-nlme=3.1_157
  - r-nnet=7.3_17
  - r-numderiv=2016.8_1.1
  - r-openssl=2.0.0
  - r-padr=0.6.0
  - r-parallelly=1.31.1
  - r-parsnip=0.2.1
  - r-patchwork=1.1.1
  - r-performanceanalytics=2.0.4
  - r-pillar=1.7.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.4
  - r-pkgmaker=0.32.2
  - r-plogr=0.2.0
  - r-plotly=4.10.0
  - r-plyr=1.8.7
  - r-png=0.1_7
  - r-polyclip=1.10_0
  - r-praise=1.0.0
  - r-precrec=0.12.7
  - r-prettyunits=1.1.1
  - r-proc=1.18.0
  - r-processx=3.5.3
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-progressr=0.10.0
  - r-promises=1.2.0.1
  - r-proxy=0.4_26
  - r-ps=1.7.0
  - r-purrr=0.3.4
  - r-qqman=0.1.8
  - r-quadprog=1.5_8
  - r-quandl=2.11.0
  - r-quantmod=0.4.20
  - r-r.methodss3=1.8.1
  - r-r.oo=1.24.0
  - r-r.utils=2.11.0
  - r-r6=2.5.1
  - r-randomforest=4.6_14
  - r-ranger=0.13.1
  - r-rappdirs=0.3.3
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.8.3
  - r-rcpparmadillo=0.11.0.0.0
  - r-rcppeigen=0.3.3.9.2
  - r-rcpproll=0.3.0
  - r-rcurl=1.98_1.6
  - r-readr=2.1.2
  - r-readxl=1.3.1
  - r-recipes=0.2.0
  - r-registry=0.5_1
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-reprex=2.0.1
  - r-reshape2=1.4.4
  - r-restfulr=0.0.13
  - r-riingo=0.3.1
  - r-rjson=0.2.21
  - r-rlang=1.0.2
  - r-rmarkdown=2.14
  - r-rngtools=1.5.2
  - r-rpart=4.1.16
  - r-rprojroot=2.0.3
  - r-rsample=0.1.1
  - r-rsqlite=2.2.8
  - r-rstudioapi=0.13
  - r-rvest=1.0.2
  - r-sass=0.4.1
  - r-scales=1.2.0
  - r-selectr=0.4_2
  - r-shape=1.4.6
  - r-shiny=1.7.1
  - r-slider=0.2.2
  - r-snakecase=0.11.0
  - r-snow=0.4_4
  - r-sourcetools=0.1.7
  - r-splitstackshape=1.4.8
  - r-squarem=2021.1
  - r-stringi=1.7.6
  - r-stringr=1.4.0
  - r-survival=3.3_1
  - r-svglite=2.0.0
  - r-sys=3.4
  - r-systemfonts=1.0.4
  - r-testthat=3.1.4
  - r-tibble=3.1.7
  - r-tictoc=1.0.1
  - r-tidymodels=0.2.0
  - r-tidyquant=1.0.3
  - r-tidyr=1.2.0
  - r-tidyselect=1.1.2
  - r-tidyverse=1.3.1
  - r-timedate=3043.102
  - r-timetk=2.8.0
  - r-tinytex=0.38
  - r-tseries=0.10_51
  - r-tsfeatures=1.0.2
  - r-ttr=0.24.3
  - r-tune=0.2.0
  - r-tweenr=1.0.2
  - r-tzdb=0.3.0
  - r-upsetr=1.4.0
  - r-urca=1.3_0
  - r-utf8=1.2.2
  - r-uuid=1.1_0
  - r-vctrs=0.4.1
  - r-venndiagram=1.6.20
  - r-viridislite=0.4.0
  - r-vroom=1.5.7
  - r-waldo=0.4.0
  - r-warp=0.2.0
  - r-withr=2.5.0
  - r-workflows=0.2.6
  - r-workflowsets=0.2.1
  - r-xfun=0.30
  - r-xml=3.99_0.9
  - r-xml2=1.3.3
  - r-xtable=1.8_4
  - r-xts=0.12.1
  - r-yaml=2.3.5
  - r-yardstick=0.0.9
  - r-zoo=1.8_10
  - ratelimiter=1.2.0
  - readline=8.1
  - requests=2.27.1
  - retry=0.9.2
  - ripgrep=13.0.0
  - rpy2=3.4.5
  - rsa=4.8
  - ruamel_yaml=0.15.80
  - s3transfer=0.5.2
  - scikit-learn=1.0.1
  - scipy=1.8.0
  - sed=4.8
  - setuptools=59.8.0
  - simplegeneric=0.8.1
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=6.0.0
  - smmap=3.0.5
  - snakemake=7.6.1
  - snakemake-minimal=7.6.1
  - snappy=1.1.8
  - soupsieve=2.3.1
  - sqlite=3.36.0
  - stack_data=0.3.0
  - stone=3.3.1
  - stopit=1.1.2
  - sysroot_linux-64=2.12
  - tabulate=0.8.9
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tktable=2.10
  - tomli=2.0.1
  - toposort=1.7
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=4.2.0
  - typing_extensions=4.2.0
  - tzdata=2022a
  - tzlocal=4.2
  - ubiquerg=0.6.1
  - unicodedata2=14.0.0
  - uritemplate=4.1.1
  - urllib3=1.26.9
  - veracitools=0.1.3
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wrapt=1.14.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - yte=1.2.2
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - absl-py==1.2.0
    - astunparse==1.6.3
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - protobuf==3.19.4
    - requests-oauthlib==1.3.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - werkzeug==2.2.1

